### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by z3t0** [deathcap/voxel-console#2]
How would I implement this in my game...

**Comment by z3t0** [comment]
A demo for this would be greatly appreciated

**Comment by z3t0** [comment]
I can't seem to figure out how I would add this to my game, I can get console-widget working by itself, using that package but I cannot figure out how Modal works to pause the game... Any help appreciated.

**Comment by z3t0** [comment]
Would it be like this?
```js
var console = require('voxel-console');
console.open():
```
Or similar

**Comment by deathcap** [comment]
You load it with [voxel-plugins](https://github.com/deathcap/voxel-plugins) (to do: add this to readme)

```javascript

require('voxel-console');

// then in your plugin options:

'voxel-console': {}

```

example https://github.com/deathcap/voxelmetaverse/blob/master/index.coffee#L149

**Comment by z3t0** [comment]
Thanks, I'm assuming that this also needs to be used with the stackgl branch of voxel-engine? If that is the case it would be useful to indicate this on the README.

**Comment by deathcap** [comment]
It works the easiest with voxel-engine-stackgl since it includes a built-in voxel-plugins, but voxel-commands has no stackgl or three.js dependencies (no graphics) so it should work with voxel-engine, as long as voxel-plugins (and the other plugin dependencies) are available

**Comment by z3t0** [comment]
ok nice
